#!/bin/bash

#nmap for ports 49153 in network. Outputs as list of IPS
IPS=`nmap -p 49153 192.168.3.101-150 -oG - | awk '/49153\/open/ {print $2}'`

#Sets the bash line seperator for some reason (don't even know when I made it) This somehow resets the output to be workable
IFS=$' '
TEST=($(echo $IPS))

#Create array of valid ips accepting wemo-like requests
mapfile -t IPAR < <( echo ${TEST[0]} )

#loops through ips and outputs the ip and its result from the wemo "GETNAME" and "GETSTATE" Commands
for i in "${IPAR[@]}"; do
	NAME=`curl --silent $i:49153/upnp/control/basicevent1 -H "Content-Type: text/xml; charset=utf-8" -H 'SOAPACTION: "urn:Belkin:service:basicevent:1#GetFriendlyName"' --data '<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetFriendlyName xmlns:u="urn:Belkin:service:basicevent:1"></u:GetFriendlyName></s:Body></s:Envelope>' | sed '3!d' | cut -f2 -d'<' | cut -f2 -d'>'`
	STATE=`curl --silent $i:49153/upnp/control/basicevent1 -H "Content-Type: text/xml; charset=utf-8" -H 'SOAPACTION: "urn:Belkin:service:basicevent:1#GetBinaryState"' --data '<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetBinaryState xmlns:u="urn:Belkin:service:basicevent:1" /></s:Body></s:Envelope>' | sed '3!d' | cut -f2 -d'<' | cut -f2 -d'>'`
	if [ "$STATE" = 1 ]; then
		STATE="ON "
	fi
	if [ "$STATE" = 0 ]; then
		STATE="OFF"
	fi
	echo -n "$i ----- "; echo -n "$STATE ------ "; echo $NAME
done
